version: '3.8'

services:
  frontend:
    image: node:alpine
    container_name: frontend
    working_dir: /app/frontend
    volumes:
      - .:/app/frontend
    ports:
      - "3000:3000"
    command: ["npm", "start"]
