version: '3.8'

services:
  frontend:
    image: node:alpine
    container_name: frontend
    working_dir: /app/frontend
    volumes:
      - .:/app/frontend
    ports:
      - "5002:3000"
    command: /bin/sh -c "npm install --force && npm start"
